# -*- coding: utf-8 -*-
"""prodigy task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_CF5bQdr0o6qTcHT4gAjyKlO0npXyM1o
"""

import matplotlib.pyplot as plt

import numpy as np

ages=[25,30,35,40,45,50,55,60,65,70,75,80]

# creating a histograph

plt.hist(ages, bins=5, edgecolor="black", alpha=0.65)
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.title("Age distribution histograph")
plt.show()

genders=["male","Female","Male","Female","Male","Female","others"]

plt.hist(genders, bins=3, edgecolor="black", rwidth=0.8)
plt.xlabel("Gender")
plt.ylabel("Count")
plt.title("Gender distribution histograph")
plt.show()

